"""Ports for pipeline orchestration backends."""

from __future__ import annotations

from typing import Protocol


class PipelineOrchestrator(Protocol):
    """Pipeline operations required by application handlers."""

    def get_pipeline_state(self, floor_plan_id: int): ...

    def detect_walls(self, floor_plan_id: int): ...

    def commit_walls(self, floor_plan_id: int, payload): ...

    def detect_openings(self, floor_plan_id: int): ...

    def commit_openings(self, floor_plan_id: int, payload): ...

    def detect_rooms(self, floor_plan_id: int): ...

    def commit_rooms(self, floor_plan_id: int, payload): ...

    def detect_zkspc(self, floor_plan_id: int): ...

    def commit_zkspc(self, floor_plan_id: int, payload): ...

